#!/bin/bash
# JSONL 기반 세션 리줌 생성 + /tmp에 저장
SESSION="$1"
SECRETARY_DIR="$(dirname "$0")/.."
REGISTRY="$SECRETARY_DIR/.session-registry.txt"
PYTHON="/c/Users/jsh86/AppData/Local/Programs/Python/Python312/python.exe"
JSONL_BASE="$HOME/.claude/projects"
RESUME_FILE="/tmp/session-resume-${SESSION}.txt"

# 레지스트리에서 세션 정보 조회
SID=$(grep "^${SESSION}|" "$REGISTRY" | cut -d'|' -f5)
DIR=$(grep "^${SESSION}|" "$REGISTRY" | cut -d'|' -f3)

JSONL_DIR="$JSONL_BASE/$(echo "$DIR" | sed 's|:|--|; s|/|--|g; s|\\|--|g')"
JSONL_FILE="$JSONL_DIR/${SID}.jsonl"
[ ! -f "$JSONL_FILE" ] && exit 1

"$PYTHON" -c "
import sys, json
from collections import OrderedDict

edits, reads, bashes, agents = [], [], [], []
for line in open(sys.argv[1]):
    try:
        d = json.loads(line)
        if d.get('type') != 'assistant': continue
        for c in d.get('message',{}).get('content',[]):
            if not isinstance(c,dict) or c.get('type')!='tool_use': continue
            name, inp = c.get('name',''), c.get('input',{})
            if name in ('Edit','Write') and 'file_path' in inp:
                edits.append(inp['file_path'])
            elif name == 'Read' and 'file_path' in inp:
                reads.append(inp['file_path'])
            elif name == 'Bash':
                bashes.append(inp.get('command','')[:100])
            elif name == 'Agent':
                agents.append(inp.get('description','')[:60])
    except: pass

# 최근 항목 우선 (역순에서 중복 제거)
def recent_unique(lst, n):
    seen = set(); result = []
    for x in reversed(lst):
        if x not in seen: seen.add(x); result.append(x)
        if len(result) >= n: break
    return result

print('## Session Resume (auto-generated by secretary)')
print()
print('### Recently Edited Files')
for f in recent_unique(edits, 10): print(f'- {f}')
print()
print('### Recently Read Files')
for f in recent_unique(reads, 8): print(f'- {f}')
print()
print('### Recent Bash Commands')
for c in recent_unique(bashes, 5): print(f'- \`{c}\`')
if agents:
    print()
    print('### Spawned Agents')
    for a in recent_unique(agents, 3): print(f'- {a}')
" "$JSONL_FILE" > "$RESUME_FILE"

# git 상태 추가
GIT_DIR=$(echo "$DIR" | sed 's|/|/|g')
echo "" >> "$RESUME_FILE"
echo "### Git State" >> "$RESUME_FILE"
git -C "$GIT_DIR" log --oneline -5 2>/dev/null >> "$RESUME_FILE" || echo "- (not a git repo)" >> "$RESUME_FILE"
git -C "$GIT_DIR" diff --stat 2>/dev/null >> "$RESUME_FILE"

echo "$RESUME_FILE"
