#!/bin/bash
# generate-session-resume.sh — 세션 맥락 복원용 리줌 생성
# 포함: 대화 흐름, last-prompt, assistant 텍스트, 편집 파일, git diff, plan.md, memory
SESSION="$1"
SECRETARY_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REGISTRY="$SECRETARY_DIR/.session-registry.txt"
PYTHON="/c/Users/jsh86/AppData/Local/Programs/Python/Python312/python.exe"
JSONL_BASE="$HOME/.claude/projects"
RESUME_FILE="/tmp/session-resume-${SESSION}.txt"

# 레지스트리에서 세션 정보 조회
SID=$(grep "^${SESSION}|" "$REGISTRY" | cut -d'|' -f5)
DIR=$(grep "^${SESSION}|" "$REGISTRY" | cut -d'|' -f3)

JSONL_DIR="$JSONL_BASE/$(echo "$DIR" | sed 's|:|--|; s|/|--|g; s|\\|--|g')"
JSONL_FILE="$JSONL_DIR/${SID}.jsonl"
[ ! -f "$JSONL_FILE" ] && exit 1

"$PYTHON" - "$JSONL_FILE" > "$RESUME_FILE" << 'PYEOF'
import sys, json

path = sys.argv[1]
last_prompt = ''
conversation = []   # (role, text) 쌍
assistant_texts = []
edit_files = []
reads = []
bashes = []
agents = []

with open(path, 'r', encoding='utf-8', errors='ignore') as f:
    lines = f.readlines()

for raw in lines:
    try:
        d = json.loads(raw)
        t = d.get('type', '')

        if t == 'last-prompt':
            lp = d.get('lastPrompt', '')
            if lp:
                last_prompt = lp

        elif t == 'user':
            for c in d.get('message', {}).get('content', []):
                if isinstance(c, dict) and c.get('type') == 'text':
                    txt = c.get('text', '').strip()
                    # system-reminder 등 자동 주입 제외
                    if txt and len(txt) > 10 and not txt.startswith('<system-reminder'):
                        conversation.append(('user', txt[:300]))

        elif t == 'assistant':
            for c in d.get('message', {}).get('content', []):
                if not isinstance(c, dict):
                    continue
                if c.get('type') == 'text':
                    txt = c.get('text', '').strip()
                    if len(txt) > 80:
                        assistant_texts.append(txt)
                        conversation.append(('assistant', txt[:400]))
                elif c.get('type') == 'tool_use':
                    name = c.get('name', '')
                    inp = c.get('input', {})
                    if name in ('Edit', 'Write') and 'file_path' in inp:
                        edit_files.append(inp['file_path'])
                    elif name == 'Read' and 'file_path' in inp:
                        reads.append(inp['file_path'])
                    elif name == 'Bash':
                        bashes.append(inp.get('command', '')[:120])
                    elif name == 'Agent':
                        agents.append(inp.get('description', '')[:60])
    except:
        pass

def recent_unique(lst, n):
    seen = set(); result = []
    for x in reversed(lst):
        if x not in seen:
            seen.add(x); result.append(x)
        if len(result) >= n:
            break
    return result

print('## Session Resume (auto-generated by secretary)')
print()

# 1. 마지막 사용자 요청
if last_prompt:
    print('### Last User Request')
    print(f'> {last_prompt}')
    print()

# 2. 최근 대화 흐름 (user↔assistant 마지막 8턴)
recent_conv = conversation[-8:]
if recent_conv:
    print('### Recent Conversation (last 8 turns)')
    for role, txt in recent_conv:
        prefix = '**User:**' if role == 'user' else '**Assistant:**'
        print(f'{prefix} {txt}')
        print()

# 3. 최근 편집/읽은 파일
print('### Recently Edited Files')
for f in recent_unique(edit_files, 10):
    print(f'- {f}')
print()

print('### Recently Read Files')
for f in recent_unique(reads, 8):
    print(f'- {f}')
print()

print('### Recent Bash Commands')
for c in recent_unique(bashes, 5):
    print(f'- `{c}`')

if agents:
    print()
    print('### Spawned Agents')
    for a in recent_unique(agents, 3):
        print(f'- {a}')
PYEOF

# 4. git 상태 — 실제 변경 내용
echo "" >> "$RESUME_FILE"
echo "### Git State" >> "$RESUME_FILE"
git -C "$DIR" log --oneline -5 2>/dev/null >> "$RESUME_FILE" || echo "- (not a git repo)" >> "$RESUME_FILE"
echo "" >> "$RESUME_FILE"
echo "#### Uncommitted Changes" >> "$RESUME_FILE"
git -C "$DIR" diff --unified=3 2>/dev/null | head -150 >> "$RESUME_FILE"
git -C "$DIR" diff --cached --unified=3 2>/dev/null | head -100 >> "$RESUME_FILE"

# 5. plan.md
PLAN_FILE="$DIR/plan.md"
if [ -f "$PLAN_FILE" ]; then
  echo "" >> "$RESUME_FILE"
  echo "### Current Plan (plan.md)" >> "$RESUME_FILE"
  head -80 "$PLAN_FILE" >> "$RESUME_FILE"
fi

# 6. MEMORY.md
MEMORY_FILE="$HOME/.claude/projects/$(echo "$DIR" | sed 's|:|--|; s|/|--|g; s|\\|--|g')/memory/MEMORY.md"
[ ! -f "$MEMORY_FILE" ] && MEMORY_FILE="$HOME/.claude/memory/MEMORY.md"
if [ -f "$MEMORY_FILE" ]; then
  echo "" >> "$RESUME_FILE"
  echo "### Memory Index (MEMORY.md)" >> "$RESUME_FILE"
  cat "$MEMORY_FILE" >> "$RESUME_FILE"
fi

echo "$RESUME_FILE"
